services:
  api-dev:
    build:
      context: .
      dockerfile: api/dockerfiles/dev/Dockerfile
    image: api:latest
    ports:
      - "3000:8080"
    env_file:
      - .env

  api-prod:
    build:
      context: .
      dockerfile: api/dockerfiles/prod/Dockerfile
    image: api:latest
    ports:
      - "5050:5050"
    env_file:
      - .env

  web-scraper:
    platform: linux/amd64 # AWS ECS default
    build:
      context: .
      dockerfile: web_scraper/Dockerfile
    image: scraper:latest
    env_file:
      - .env
