services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env

  web-scraper:
    platform: linux/amd64 # AWS ECS default
    build:
      context: .
      dockerfile: web_scraper/Dockerfile
    image: scraper:latest
    env_file:
      - .env
